---
- name: Check if Composer is installed
  ansible.builtin.stat:
    path: "{{ php_composer_install_path }}"
  register: php_composer_binary

- name: Install packages needed to install Composer
  ansible.builtin.apt:
    name: wget
    state: present
  when: not php_composer_binary.stat.exists

- name: Create the install script
  ansible.builtin.template:
    src: composer-install.sh.j2
    dest: /tmp/composer-install.sh
    mode: "0755"
  when: not php_composer_binary.stat.exists

- name: Install Composer
  ansible.builtin.command: ./composer-install.sh
  args:
    chdir: /tmp
  when: not php_composer_binary.stat.exists
  changed_when: false

- name: Remove the install script
  ansible.builtin.file:
    path: /tmp/composer-install.sh
    state: absent
  when: not php_composer_binary.stat.exists

- name: Move Composer to the install path
  ansible.builtin.command: mv /tmp/composer.phar "{{ php_composer_install_path }}"
  when: not php_composer_binary.stat.exists
  changed_when: false

- name: Enable the wrapper
  ansible.builtin.template:
    src: composer.j2
    dest: "{{ php_composer_wrapper_path }}"
    mode: "0755"
  when: php_composer_wrapper_enabled | bool
